apiVersion: v2
name: metr
version: "2"
description: security shart for metrics
type: application
home: https://github.com/tulamelkii
dependencies: 
  - name: memcached
    version: 6.14.0 
    repository: https://charts.bitnami.com/bitnami 
