apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  labels:
    app: nginx-service-monitor
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: scrape
      path: /metrics
