apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.spec.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.spec.maxUnavailable }}
  selector:
    matchLabels:
      {{- .Values.spec.selector.mLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- .Values.spec.template.label | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.specont.sa }}
      containers:
      - name: cont-{{ .Chart.Name }}
        image: {{ .Values.specont.containers.images.rep }}:{{ .Values.specont.containers.images.tag }} 
        lifecycle:
          preStop:
            exec:
              command: {{ .Values.specont.containers.preStop.comand }}
        ports:
        - containerPort: {{ .Values.specont.containers.port }}
        volumeMounts:
        - mountPath: {{ .Values.volumeMounts.mountPath }}
          name: volume-{{ .Chart.Name }}
        - mountPath: {{ .Values.volumeMounts.nginxPath }}
          name: vol-nginx-{{ .Chart.Name }}
          subPath: {{ .Values.volumeMounts.subPath }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .Values.httpGet.path }}
            port: {{ .Values.specont.containers.port }}
          initialDelaySeconds: {{ .Values.httpGet.initialDelaySeconds }}
          periodSeconds: {{ .Values.httpGet.periodSeconds }}
        {{- end }}
      initContainers: 
      - name: init-cont-{{ .Chart.Name }}
        image: {{ .Values.initContainers.image.repo }}:{{ .Values.initContainers.image.tags }}
        command: ["sh", "-c", '{{ .Values.initContainers.command }}' ]
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: mysecret-{{ .Chart.Name }}
                key: token
        volumeMounts:
        - mountPath: {{ .Values.mountPath.mount }}         
          name: volume-{{ .Chart.Name }}
      volumes:
      - name: volume-{{ .Chart.Name }}
        persistentVolumeClaim:
           claimName: pvc-volume2     
      - name: vol-nginx-{{ .Chart.Name }}
        configMap:
          name: cmnginx-{{ .Chart.Name }}

