apiVersion: v1
kind: Secret
metadata:
  name: mysecret-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.specont.sa }}
type: kubernetes.io/service-account-token

