apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: service-nginx-{{ .Chart.Name}}
spec:
  selector:
    {{- .Values.spec.template.label | nindent 4 }}
  ports:
  - protocol: TCP
    name: tcp-service-{{ .Chart.Name}}
    port: {{ .Values.specingress.port }}
    targetPort: {{ .Values.specont.containers.port }}
