apiVersion: v1
data:
  home.conf: "server {\n    listen       8000;\n    listen  [::]:8000;\n    server_name
    \ localhost;\n\n    location /metrics {\n        root   /homework;\n        index  metrics.html;\n    }\n\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cmnginx
  namespace: homework
