apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume2
  namespace: homework
spec:
  storageClassName: "myprovision"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

