apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RBcd
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: scd
    namespace: homework
roleRef:
    kind: Role
    name: RoleCd
    apiGroup: rbac.authorization.k8s.io
