apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{- include "metrics.fullname" . }}
  namespace: {{ include "metrics.namespace" . }}
spec:
  storageClassName: storclass-{{- include "metrics.name" . }}
  accessModes:
  - {{ .Values.specPvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.specPvc.resources.storage }}

