apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-cd-{{- include "metrics.name" . }}
  namespace: {{ include "metrics.namespace" . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  

