apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-monitoring-{{- include "metrics.name" . }}
  namespace: {{ include "metrics.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes/metrics"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["/metrics"]
    verbs: [ "get"]

  - apiGroups: [""]
    resources: ["pod"]
    verbs: ["create","watch","delete","update","list"]
