apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RBcd
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: scd
    namespace: {{ .Values.namespace }}
roleRef:
    kind: Role
    name: RoleCd
    apiGroup: rbac.authorization.k8s.io
