apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RBmonitoring
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.specont.sa }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: rmonitoring
  apiGroup: rbac.authorization.k8s.io

    

