apiVersion: v1
kind: Secret
metadata:
  name: mysecret-{{- include "metrics.name" . }}
  namespace: {{ include "metrics.namespace" . }}

  annotations:
    kubernetes.io/service-account.name: sa-monitoring-{{- include "metrics.name" . }}
type: kubernetes.io/service-account-token

