apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storclass-{{- include "metrics.name" . }}
  labels:
    #    stor-retain-{{- include "metrics.labels" . | indent 4 }}
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
