repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  createNamespace: True
  timeout: 800
  wait: True

releases: 
  - name: kafka
    chart: bitnami/kafka
    namespace: prod
    set:
      - name: replicaCount
        value: 5
      - name: image.tag
        value: "3.5.2"
      - name: client.protocol
        value: "SASL_PLAINTEXT"
      - name: interbroker.protocol
        value: "SASL_PLAINTEXT"
  - name: dev
    namespace: dev
    chart: bitnami/kafka
    set:
      - name: image.tag
        value: "latest"
      - name: broker.replicaCount
        value: 1
      - name: listeners.client.protocol
        value: "PLAINTEXT"
      - name: listeners.interbroker.protocol
        value: "PLAINTEXT"
        
