repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases: 
  - name: kafka
    chart: bitnami/kafka
    namespace: prod
    set:
      - name: replicaCount
        value: 4
      - name: image.tag
        value: "3.5.2"
      - name: client.protocol
        value: "SASL_PLAINTEXT"
      - name: interbroker.protocol
        value: "SASL_PLAINTEXT"
      - name: enabledMechanisms
        value: "PLAIN"
      - name: interBrokerMechanism
        value: "PLAIN"
        
