apiVersion: v1
kind: Pod
metadata:
  name: static-web
  label:
    name: static-web
spec:
  containers:
  - name: web-nginx
    image: nginx:latest
    volumeMounts:
    - mounthPath: /homework
      name: volume
    ports:
    - containerPort: 8000
      targetPort: 80

  initContainers:
  - name: init-containers
    image: busybox:latest
    command: ['sh', '-c', 'wget'
    volumeMounts:
    - mounthPath: /init
      name: volume
  
  volumes:
  - name: volume
    emptyDir:
      sizeLimit: 800Mi

